spring.application.name=ihsolar

# Server
server.port=8081
server.servlet.context-path=/

# Database
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# JSP
spring.mvc.view.enabled=false
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/views/
spring.thymeleaf.suffix=.html

# MSG
spring.messages.basename=msg/messages
spring.messages.encoding=UTF-8

# Log
logging.level.root=INFO

# Dev
spring.devtools.restart.enabled=true