biznexus.req-tag.ip = [APIIP]
#\uc11c\ubc84 \uc5c5\ub370\uc774\ud2b8 \uc2dc \uc544\ub798\uc8fc\uc11d \ud480\uace0 \uc704 \uc8fc\uc11d\ucc98\ub9ac
#biznexus.req-tag.ip = 127.0.0.1
biznexus.req-tag.port = 8203
