{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.7.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.18"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.18"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.18"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.31"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.18.jar",
          "url": "spring-boot-starter-data-jpa-2.7.18.jar",
          "size": 4759,
          "sha512": "5173b0b50028f667d79ebb4783e963595122aee39c002143decd89ea374addb180a99a3fa708039fde54b3d5b4d255a110c61b1788e03ee2a8012a5ff97b61cc",
          "sha256": "2183eff6cdb42cc03f9057f092a56cf10c2f1d4eb0b9a0d0df9356f588250a74",
          "sha1": "ffc6aa225da2a9987238ad88ae4550e5ee68da61",
          "md5": "f7fd64bec96636a8cca7815130c61733"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.18"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.18"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.18"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.31"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.18.jar",
          "url": "spring-boot-starter-data-jpa-2.7.18.jar",
          "size": 4759,
          "sha512": "5173b0b50028f667d79ebb4783e963595122aee39c002143decd89ea374addb180a99a3fa708039fde54b3d5b4d255a110c61b1788e03ee2a8012a5ff97b61cc",
          "sha256": "2183eff6cdb42cc03f9057f092a56cf10c2f1d4eb0b9a0d0df9356f588250a74",
          "sha1": "ffc6aa225da2a9987238ad88ae4550e5ee68da61",
          "md5": "f7fd64bec96636a8cca7815130c61733"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.18.jar",
          "url": "spring-boot-starter-data-jpa-2.7.18.jar",
          "size": 4759,
          "sha512": "5173b0b50028f667d79ebb4783e963595122aee39c002143decd89ea374addb180a99a3fa708039fde54b3d5b4d255a110c61b1788e03ee2a8012a5ff97b61cc",
          "sha256": "2183eff6cdb42cc03f9057f092a56cf10c2f1d4eb0b9a0d0df9356f588250a74",
          "sha1": "ffc6aa225da2a9987238ad88ae4550e5ee68da61",
          "md5": "f7fd64bec96636a8cca7815130c61733"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.18"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.18.jar",
          "url": "spring-boot-starter-data-jpa-2.7.18.jar",
          "size": 4759,
          "sha512": "5173b0b50028f667d79ebb4783e963595122aee39c002143decd89ea374addb180a99a3fa708039fde54b3d5b4d255a110c61b1788e03ee2a8012a5ff97b61cc",
          "sha256": "2183eff6cdb42cc03f9057f092a56cf10c2f1d4eb0b9a0d0df9356f588250a74",
          "sha1": "ffc6aa225da2a9987238ad88ae4550e5ee68da61",
          "md5": "f7fd64bec96636a8cca7815130c61733"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.18-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.7.18-javadoc.jar",
          "size": 4750,
          "sha512": "ad6b22f6efc5efda1eb667b0679bd73effa0fe6934dc3c0965691d4a088ad93e2d49e801d3895c0a4899c1d31585673010c74aa3f069b0a51c68e7fa4e7a2e92",
          "sha256": "653e2626b71817d090fe7904259487cbe088a41d0ac7e176dc2673cf2be73e5c",
          "sha1": "2804e0d4f5bb3266a6e34dc5674a79fa93a249cf",
          "md5": "fb726dbf6dd96412cae6a0b55e8e0536"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.18-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.7.18-sources.jar",
          "size": 4748,
          "sha512": "59415a717bf3b37f3804c407af8101f19fb819bc81c06ee40e442651194180200c724f33a46de4b40893858f3eeb8875dacc0c0687b3a8ff913c1810f0d6e39f",
          "sha256": "71e9d69b1cb06cc61382348d87e83d996c1dc2ab08f4d6310d4f77e4388d6424",
          "sha1": "43b868bc40c9f6ce7f763180cfbfc6b3d2303629",
          "md5": "0b3dccee35943b24f8f12af2d96a84ea"
        }
      ]
    }
  ]
}
